const SOURCE_SAMPLE_RATE = 48000
const ANALYSIS_SAMPLE_RATE = 4000
const ANALYSIS_MIN_FREQUENCY = 20
const ANALYSIS_MAX_FREQUENCY = 1000
const FFT_SIZE = 2048
const WINDOW_SIZE = 2048
const HOP_SIZE = Math.round(WINDOW_SIZE / 3)
const DECIMATOR_CUTOFF_HZ = 1500
const DECIMATOR_TAP_COUNT = 129

module.exports = {
  SOURCE_SAMPLE_RATE,
  ANALYSIS_SAMPLE_RATE,
  ANALYSIS_MIN_FREQUENCY,
  ANALYSIS_MAX_FREQUENCY,
  FFT_SIZE,
  WINDOW_SIZE,
  HOP_SIZE,
  DECIMATOR_CUTOFF_HZ,
  DECIMATOR_TAP_COUNT
}
